theme: jekyll-theme-cayman
layout: post
title: coLAB Data
description: Public repository for open datasets and scripts by the Research Laboratory for Communication, Political Cultures and Economies of Collaboration, Fluminense Federal University<br>Repositório de dados e <em>scripts</em> públicos do<br>Laboratório de Pesquisa em Comunicação, Culturas Políticas e Economia da Colaboração, Universidade Federal Fluminense
show_downloads: false
